# Generated by Django 3.2.7 on 2021-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_productos', models.CharField(max_length=50)),
                ('cantidad_venta_producto', models.IntegerField()),
                ('precio_total', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
    ]
