# Generated by Django 3.2.7 on 2021-10-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_rename_nombre_producto_venta_nombre_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='venta',
        ),
    ]
